test_datasets: ['svhn', 'usps','mnistm', 'mnist']
train_datasets: ['mnist'] 
im_size: 28

net1: 'a'
batch_size: 64
num_classes: 10
epochs: 100
lr: 0.01 
loss: 'contrastive_loss'
optimizer: 'sgd' 
with_masks: False
handwritten_masks: True

pseudo_siamese: False
siamese: True


outdir: './outputs/siamese/handwritten/'
