test_datasets: ['svhn', 'usps','mnistm', 'mnist']
train_datasets: ['svhn'] 
im_size: 32

net1: 'cnn2'
batch_size: 64
num_classes: 10
epochs: 1000
lr: 0.01 
loss: 'categorical_crossentropy'
optimizer: 'sgd' 
with_masks: False
handwritten_masks: False

pseudo_siamese: False
siamese: False


outdir: './outputs/baseline/without_masks/'

