test_datasets: ['svhn', 'usps','mnistm', 'mnist']
train_datasets: ['usps'] 
im_size: 32

net1: 'vada'
batch_size: 128
num_classes: 10
epochs: 1000
lr: 0.001 
loss: 'contrastive_loss'
optimizer: 'sgd' 
with_masks: False
handwritten_masks: False

pseudo_siamese: False
siamese: True


outdir: './outputs/siamese/not_handwritten2/'
